Review branch
awais-amjed/js-best-practices-review pull request #1
Opened 2022-02-21 08:10 UTC by awais-amjed

In this PR, following change was made:

- Added the Code from To-Do List Project. ✅

2022-02-21 16:00 UTC, mwafrika requested changes
# Summary review of the todo list 
- Try to reduce the number of parameters in your function
- Add a value for the ALT attribute for your image

2022-02-21 16:00 UTC, mwafrika commented on src/index.html
> +            </form>
I think it's good if you add a value for the ALT attribute in your image tag for good accessibility

2022-02-21 16:00 UTC, mwafrika commented on src/modules/html_functions.js
> +  }
Please consider using a few numbers of parameters in your function declaration,

2022-02-21 16:00 UTC, mwafrika commented on src/modules/html_functions.js
> +  } else {
The number of parameters should be fewer

2022-02-21 16:09 UTC, awais-amjed commented on src/modules/html_functions.js
> +  } else {
@mwafrika I thought You were talking about destructing class members... But I can't make the parameters of this function any lesser since it needs all of them.

2022-02-21 16:10 UTC, awais-amjed commented on src/index.html
> +            </form>
Thanks for the review I will implement this.

2022-02-21 18:50 UTC, mwafrika commented on src/modules/html_functions.js
> +  } else {
Hello @awais-amjed  can you check this for reference? I can update anything you want, It's an exercise and I am trying to give suggestions if you have something you would like to discuss, You can do it for sure and this can be the opportunity to clarify things if I am wrong. 

![best practice](https://user-images.githubusercontent.com/25848053/155011988-ec4f1368-8769-4b39-9fb7-985684bb0ad6.png)

2022-02-22 09:25 UTC, mwafrika commented
Good job. congratulations @awais-amjed  Your project is complete now. It's time to merge it now.

2022-02-22 11:54 UTC, merged